### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by hcientist** [acbart/waltz#2]
Does it make sense to get started by having waltz grab my course directly out of canvas in order to init my offline copy? If so, how do?

**Comment by acbart** [comment]
Oof, my documentation is probably not up to this yet. In theory, yes, once you've set up your config file, you should be able to start off by doing something like:

```
python waltz pull --course cisc108_fall19 --destination ~/courses/cisc108/fall19/
```

And that would pull all the assignments, quizzes and pages. But again, I don't think the documentation is there yet.

But this is funny timing, because I promised Phill and Mike an interactive demo at our next meeting (sometime next week). So I actually have some incentive to get that cleaned up and workable by people who are not me. If you can wait a few days for me to wrap up the semester grading, I'll get the starter instructions written up.

I'll be super interested in hearing your thoughts on how this is shaping up. I've been making a lot of use out of Waltz this past year, but it still has a bunch of features I still want.

**Comment by acbart** [comment]
So you may have noticed I've pushed some changes - take a look at this branch to see the latest version (with instructions) that uses a different API. I still have a few features to work out, but the minimal functionality should be there: https://github.com/acbart/waltz/tree/v2

**Comment by acbart** [comment]
Actually, I just merged that branch into master. No reason to keep working on a separate branch now that the core functionality is there.
